ALTER TABLE games ADD COLUMN IF NOT EXISTS fen TEXT NOT NULL DEFAULT 'rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1';
ALTER TABLE games ADD COLUMN IF NOT EXISTS time_control INT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS red_time INT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS black_time INT;
